variables:
  random: &random
    min: 0
    max: 29
    step: 1
    default: 2
  range: &range
    formula: 15
    language: js
  moveFrequency: &moveFrequency
    formula: 1/20
    language: js

export:
  - time

seeds:
  scenario: *random
  simulation: *random

incarnation: scafi

environment:
  type: Continuous2DEnvironment
  parameters: []

network-model:
  type: ConnectWithinDistance #*connectionType
  parameters: [*range]

pools:
  - pool: &program
      - time-distribution:
          type: ExponentialTime
          parameters: [1]
        type: Event
        actions:
          - type: RunScafiProgram
            parameters: [it.unibo.casestudy.Workflow, 5.0] # second argument is retention time
      - program: send
  - pool: &move
      - time-distribution: *moveFrequency
        type: Event
        actions: []

displacements:
  - in:
      type: Grid
      parameters: [0, 0, 200, 80, 10, 10, 1, 1]
    programs:
      - *move
      - *program
    contents:
      - molecule: test
        concentration: true